//! PostgreSQL schema and migrations for the incident domain (Milestone
//! 5B-2), plus the Phase 5B-1 dependency probe this crate started as.
//!
//! **Status: schema and migrations only.** [`migrations`] embeds the
//! forward-only, checksummed SQL migrations under `migrations/` (ADR
//! 0024) that build the tables, constraints, and indexes
//! [`docs/architecture/incident-persistence.md`](../../../docs/architecture/incident-persistence.md)
//! describes. **No `IncidentStore` implementation, no connection pool
//! wiring, no repository, no HTTP, no CLI exists here yet** — that is
//! Milestone 5B-3 onward, out of scope for this crate as it stands. See
//! `README.md` for how to run the migrations against an ephemeral,
//! local-or-CI-only PostgreSQL instance, and
//! [ADR 0029](../../../docs/architecture/decisions/0029-phase5b-repository-and-unit-of-work-seam.md)
//! for why this crate — rather than a throwaway scratch crate — is where
//! that eventual `IncidentStore` implementation will live.
//!
//! This crate also still carries the Phase 5B-1 dependency probe
//! (`docs/development/follow-ups.md` FU-42): the six
//! conditionally-accepted dependencies (ADR 0019, 0020, 0022, 0023, 0024)
//! are referenced by name in [`_probe_every_dependency_links`] so a
//! normal `cargo build` actually links every one of them.
#![allow(dead_code, unused_imports)]

/// Forward-only, checksummed SQL migrations (Milestone 5B-2, ADR 0024).
///
/// Generated by [`refinery::embed_migrations!`] from the `.sql` files
/// under `migrations/` at this crate's root — each migration is compiled
/// into the binary (so a deployed binary carries its own schema history,
/// no separate file distribution step needed) while staying reviewable
/// as ordinary, individually diffable SQL files in this repository (ADR
/// 0024's follow-up explicitly left "embedded vs. file-based" open;
/// this is the 5B-2 resolution — embedded, file-based source).
///
/// See `README.md` for how to run these against an ephemeral PostgreSQL
/// instance, and `tests/migration_smoke_test.rs` for the test that
/// applies them, asserts re-application is a no-op, and checks the
/// resulting schema shape.
pub mod migrations {
    refinery::embed_migrations!("migrations");
}

/// Never called. Exists only so every probed dependency's crate root is
/// referenced by name, forcing the compiler to actually resolve and link
/// each one rather than merely list it in `Cargo.toml`.
fn _probe_every_dependency_links() {
    let _: fn(uuid::Timestamp) -> uuid::Uuid = uuid::Uuid::new_v7;
    let _ = std::any::type_name::<tokio_postgres::Client>();
    let _ = std::any::type_name::<deadpool_postgres::Pool>();
    let _ = std::any::type_name::<rustls::ClientConfig>();
    let _ = std::any::type_name::<tokio_postgres_rustls::MakeRustlsConnect>();
    let _ = std::any::type_name::<refinery::Report>();
    let _ = std::any::type_name::<dyn wetechinetmon_incident::store::IncidentStore>();
}
