//! PostgreSQL persistence for the incident domain: schema and migrations
//! (Milestone 5B-2), the staging store for ADR 0034's load–run–flush
//! (5B-3(a)), the incident row mapping and its SQL (5B-3(b)), plus the
//! Phase 5B-1 dependency probe this crate started as.
//!
//! [`migrations`] embeds the forward-only, checksummed SQL migrations
//! under `migrations/` (ADR 0024) that build the tables, constraints, and
//! indexes
//! [`docs/architecture/incident-persistence.md`](../../../docs/architecture/incident-persistence.md)
//! describes. [`staging`] is the in-memory `IncidentStore` one unit-of-work
//! call runs against. [`row`] maps an incident to column values and back;
//! [`sql`] inserts, version-guard updates and loads one incident.
//! **Not here yet:** loading a call's whole working set, flushing the
//! history tables, the transaction wrapper and retry, connection pool
//! wiring, HTTP and CLI. Those are the rest of 5B-3 onward. See
//! `README.md` for how to run the migrations against an ephemeral,
//! local-or-CI-only PostgreSQL instance, and
//! [ADR 0029](../../../docs/architecture/decisions/0029-phase5b-repository-and-unit-of-work-seam.md)
//! for why this crate — rather than a throwaway scratch crate — is where
//! that eventual `IncidentStore` implementation will live.
//!
//! This crate also still carries the Phase 5B-1 dependency probe
//! (`docs/development/follow-ups.md` FU-42): the six
//! conditionally-accepted dependencies (ADR 0019, 0020, 0022, 0023, 0024)
//! are referenced by name in [`_probe_every_dependency_links`] so a
//! normal `cargo build` actually links every one of them.
#![allow(dead_code, unused_imports)]

/// Forward-only, checksummed SQL migrations (Milestone 5B-2, ADR 0024).
///
/// Generated by [`refinery::embed_migrations!`] from the `.sql` files
/// under `migrations/` at this crate's root — each migration is compiled
/// into the binary (so a deployed binary carries its own schema history,
/// no separate file distribution step needed) while staying reviewable
/// as ordinary, individually diffable SQL files in this repository (ADR
/// 0024's follow-up explicitly left "embedded vs. file-based" open;
/// this is the 5B-2 resolution — embedded, file-based source).
///
/// See `README.md` for how to run these against an ephemeral PostgreSQL
/// instance, and `tests/migration_smoke_test.rs` for the test that
/// applies them, asserts re-application is a no-op, and checks the
/// resulting schema shape.
pub mod migrations {
    refinery::embed_migrations!("migrations");
}

/// The in-memory staging store for ADR 0034's load–run–flush
/// (Milestone 5B-3(a)). No SQL; the load and flush statements that fill
/// and drain it are 5B-3(b).
pub mod staging;

/// Errors from the row mapping and the SQL layer.
pub mod error;

/// Pure mapping between an incident and its row values (5B-3(b)).
pub mod row;

/// Insert, version-guarded update and load of one incident (5B-3(b)).
pub mod sql;

/// Pure mapping for detection-event links, timeline, audit, outbox and
/// idempotency rows (5B-3(b)).
pub mod history;

/// The load step: one call's working set into a staging store (5B-3(b)).
pub mod load;

/// The flush step: one call's change set into the database (5B-3(b)).
pub mod flush;

/// One load–run–flush transaction per unit-of-work entry point (5B-3(b)),
/// rerun from a fresh load on a transient failure (5B-3(c)).
pub mod service;

/// Which failures are transient, and the backoff between attempts (5B-3(c)).
pub mod retry;

/// The outbox consumer: claim under a lease, publish, retry, dead-letter
/// (5B-4, ADR 0033).
pub mod outbox;

/// Retention jobs for the persistence retention table (5B-4).
pub mod retention;

/// The explicitly authorized path for cross-tenant maintenance (5B-5,
/// ADR 0032).
pub mod platform;

/// Failure injection at each flush commit point, behind the
/// `fault-injection` feature (5B-5).
pub mod fault;

/// The production UUIDv7 incident id generator (ADR 0019, 5B-5).
pub mod id;

/// The connection pool: bounded waits, verified reuse (ADR 0022, 5B-5).
pub mod pool;

/// The verifying rustls connector and the no-plaintext-off-loopback rule
/// (ADR 0023, 5B-5).
pub mod tls;

/// Never called. Exists only so every probed dependency's crate root is
/// referenced by name, forcing the compiler to actually resolve and link
/// each one rather than merely list it in `Cargo.toml`.
fn _probe_every_dependency_links() {
    let _: fn(uuid::Timestamp) -> uuid::Uuid = uuid::Uuid::new_v7;
    let _ = std::any::type_name::<tokio_postgres::Client>();
    let _ = std::any::type_name::<deadpool_postgres::Pool>();
    let _ = std::any::type_name::<rustls::ClientConfig>();
    let _ = std::any::type_name::<tokio_postgres_rustls::MakeRustlsConnect>();
    let _ = std::any::type_name::<refinery::Report>();
    let _ = std::any::type_name::<dyn wetechinetmon_incident::store::IncidentStore>();
}
