[package]
name = "wetechinetmon-common"
description = "Shared types and utilities used across WetechiNetMon crates."
version.workspace = true
edition.workspace = true
license.workspace = true
publish.workspace = true

[dependencies]
thiserror.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
